### PR TITLE
set the maximum volume by setting sound in the elementary-tweaks

### PR DESCRIPTION
**Pull request by lvitals**
set the maximum volume by setting the sound in the elementary settings for low power devices such as a laptop or headset

### CODE REVIEW

**Comment by lvitals** [comment]
The problem is to make the volume control accept values greater than 100%, just like the "wingpanel-indicator-sound".


captura de tela de 2018-12-22 09-45-55

When I change "elementary-tweaks", the "switchboard-plug-sound" does not accept values greater than 100%, I need this on my laptop, even distorting the sound a bit.

captura de tela de 2018-12-22 09-51-20

captura de tela de 2018-12-22 10-00-33

**Comment by lvitals** [comment]
screencast from 2018-12-22 10 36 06

**Comment by jeremypw** [comment]
Elementary-tweaks is not supported by elementary so I am not sure how the UX team will regard this.  If setting the maximum volume is something that is desired (regardless of elementary-tweaks) then you should raise an issue against the sound plug itself and avoid mentioning elementary tweaks ;-).

**Comment by lvitals** [comment]
Yes, Gnome DE also makes this change in the Gnome Tweaks (Tweaks) tool, the Sound Enable Super-Amplification

**Comment by jeremypw** [comment]
Ah, yes - I see that there is a setting org.gnome.desktop.sound.allow-volume-above-100-percent.  Perhaps the elementary sound plug should honor that in the UI?  I would think that more likely to be accepted.

**Comment by jeremypw** [comment]
@lvitals Are you interested in pursuing an "elementary-tweaks free" solution to this?

**Comment by jeremypw** [comment]
Closing as author has not responded.

**Pull request closed without merging**
